name: Docker Image CI

on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build ./ -t bmiki75/auto-extract:latest
      - name: push image to docker hub
        run: |
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
          username: bmiki75
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push bmiki75/auto-extract:latest

